local Types = require(script.Parent.Parent:WaitForChild("Types"))

return {
	["Common"] = {
		Labubus = {
			["Lychee Berry"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Soy Milk"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Noob"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Sesame Bean"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
	["Uncommon"] = {
		Labubus = {

			["Chef"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Toffee Candy"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Chill"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
	["Rare"] = {
		Labubus = {
			["Astronaut"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Love"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Sea Salt Coconut"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
	["Epic"] = {
		Labubus = {
			["Green Grape"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Ninja"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Chestnut Cocoa"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
	["Legendary"] = {
		Labubus = {
			["Viking"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Beach"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Squid"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
	["Divine"] = {
		Labubus = {
			["Angel"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Loyalty"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
	["Secret"] = {
		Labubus = {
			["King"] = {
				Income = 1,
				SellPrice = 1,
			},
			["Secret Labubu"] = {
				Income = 1,
				SellPrice = 1,
			},
		},
	},
} :: { [Types.Rarity]: Types.LabubuRarityInfo }
